// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbgdE9jRvvF-qdrtpPyzQoPK2g7v4giFk',
    appId: '1:542530713919:web:1c0c5369e42b844a95fb8a',
    messagingSenderId: '542530713919',
    projectId: 'fooddeliverytuto-c0337',
    authDomain: 'fooddeliverytuto-c0337.firebaseapp.com',
    storageBucket: 'fooddeliverytuto-c0337.appspot.com',
    measurementId: 'G-TT3XKNBXLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZONuveQdk6zehsXsM8Qfg4K367tK996M',
    appId: '1:542530713919:android:bef70ef48ee79a2b95fb8a',
    messagingSenderId: '542530713919',
    projectId: 'fooddeliverytuto-c0337',
    storageBucket: 'fooddeliverytuto-c0337.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp2vF6oCXvqE3B1vxgzh5j2IXbOOQprhQ',
    appId: '1:542530713919:ios:24efc4f32d4bb14e95fb8a',
    messagingSenderId: '542530713919',
    projectId: 'fooddeliverytuto-c0337',
    storageBucket: 'fooddeliverytuto-c0337.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp2vF6oCXvqE3B1vxgzh5j2IXbOOQprhQ',
    appId: '1:542530713919:ios:24efc4f32d4bb14e95fb8a',
    messagingSenderId: '542530713919',
    projectId: 'fooddeliverytuto-c0337',
    storageBucket: 'fooddeliverytuto-c0337.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbgdE9jRvvF-qdrtpPyzQoPK2g7v4giFk',
    appId: '1:542530713919:web:fb1dd84ccc25b07b95fb8a',
    messagingSenderId: '542530713919',
    projectId: 'fooddeliverytuto-c0337',
    authDomain: 'fooddeliverytuto-c0337.firebaseapp.com',
    storageBucket: 'fooddeliverytuto-c0337.appspot.com',
    measurementId: 'G-DHN0K3RKDW',
  );
}
